apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: willnjl/kub-data-demo:1
          volumeMounts:
            - mountPath: /app/story/ #internal path for the directory
              name: story-volumes
      volumes:
        - name: story-volumes
          emptyDir: {} #empty object indidicates defaults